### ISSUE TITLE
Adding UTF-8 support

### ISSUE THREAD

**Issue by Abdulmajeed-Alrajhi** [Edinburgh-Genome-Foundry/blabel#18] opened 2022-04-29 22:03 UTC
There issue with item_template with Arabic language its show strange character 

i solved by edit the blabel.py line93 

before 
`with open(item_template_path) as f:`
After 
`with open(item_template_path, 'r',encoding='utf-8') as f:`

i hope there way to determine the encoding by passing argument 

Thanks

**Comment by veghp** [comment] 2022-05-01 11:24
Thanks for bringing attention to this. The cause of the problem is that Python uses the platform's encoding. More details here: https://stackoverflow.com/a/36316351/6574993 . I post two solutions:

You can load in the template with the correct encoding and specify `item_template` instead:
```python
with open("template.html", "r", encoding="utf-8") as f:
    item_template = f.read()
label_writer = LabelWriter(item_template=item_template, default_stylesheets=("style.css",))
```

And I also added an `encoding` parameter as I see no harm in doing that (https://github.com/Edinburgh-Genome-Foundry/blabel/commit/cc22c2e8ec681acb52270cad006c24896e53fbfb). To keep it backward-compatible, the default still uses the platform's encoding. This commit will be part of the next release.
```python
label_writer = LabelWriter("template.html", default_stylesheets=("style.css",), encoding="utf-8")
```

**Closed as completed** 2022-05-06 15:39 UTC
